landing page test
taniarascia/takenote pull request #463
Opened 2020-12-06 02:11 UTC by giranezafiacre

## Description

- [ ] added test of landingPage.tsx

Closes https://github.com/taniarascia/takenote/issues/419
### Browser checklist

This PR has been tested in the following browsers:

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### Testing checklist

- [ ] End-to-end tests have been created if necessary

2020-12-11 22:15 UTC, taniarascia commented
Why are the `@resources` changed to `../../resources`? Also, a test of the landing page should test the logic, like isDemo and isMobile.

2020-12-12 10:50 UTC, giranezafiacre commented
> Why are the `@resources` changed to `../../resources`? Also, a test of the landing page should test the logic, like isDemo and isMobile.

@taniarascia I tried to test with alias `@resources` as it was but there is an error that always appear maybe you can help,and to test logic of "ismobile" and "isDemo" I am still figuring out.
![landingtest](https://user-images.githubusercontent.com/51242074/101981858-92b4da00-3c78-11eb-8c0f-7dbe9e78d89b.PNG)

2021-01-25 23:10 UTC, kodyclemens requested changes

2021-01-25 23:10 UTC, kodyclemens commented on config/jest.config.js
> +    '^[@./a-zA-Z0-9$_-]+\\.(png|svg|gif)$': '<rootDir>/tests/__mocks__/styleMock.ts',
Why was this added? The map is never used and seems unnecessary.

2021-01-25 23:10 UTC, kodyclemens commented on tests/unit/client/Landing.test.tsx
> +    Object.assign(rdd, { isMobile: true })
This assign is doing nothing except making a new object that is not used. With this approach I assume you are trying to [mock an import](https://dev.to/lmeromy/testing-react-components-how-to-mock-imports-with-jest-1k90) in `<LandingPage />`?

2021-04-01 13:24 UTC, taniarascia commented
Closing due to inactivity.

2021-04-01 13:24 UTC, closed without merging